trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  DOCKER_BUILDKIT: 1
  containerRegistry: containerRegistryCurrencyConvert
  repository: $(Build.Repository.Name)
  tags: "$(Build.BuildNumber)\nlatest"

jobs:
  - job: CI-continuos-integration
    timeoutInMinutes: 10
    cancelTimeoutInMinutes: 2
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: "22.x"
        displayName: "Install Node.js"
      - script: npm install
        displayName: "Install node module dependencies from NPM"

      - script: npm run test
        displayName: "Run the test pipeline"

      # Login
      - task: Docker@2
        displayName: Docker login
        inputs:
          command: login
          containerRegistry: $(containerRegistry)

      # Build
      - task: Docker@2
        displayName: Docker build
        inputs:
          command: build
          containerRegistry: $(containerRegistry)
          repository: $(repository)
          arguments: --cache-from $(containerRegistry).azurecr.io/$(repository):latest --build-arg BUILD_NUMBER=$(Build.BuildNumber) --build-arg BUILDKIT_INLINE_CACHE=1
          tags: $(tags)

      # Logout
      - task: Docker@2
        displayName: Docker logout
        inputs:
          command: logout
          containerRegistry: $(containerRegistry)
