services:
  back-end:
    container_name: currency-converter
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    env_file: .env
    volumes:
      - .:/app
      - /app/node_modules
